# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portfolio < Formula
  desc "Local-first project inventory and knowledge platform"
  homepage "https://github.com/shafi-/portfolio"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shafi-/portfolio/releases/download/v0.3.0/portfolio-darwin-amd64"
      sha256 "3c39bbc65afaa2bcc714a7a29aadd411485104bf51d146aac98a43edb11c34db"

      def install
        bin.install "portfolio"
      end
    end
    on_arm do
      url "https://github.com/shafi-/portfolio/releases/download/v0.3.0/portfolio-darwin-arm64"
      sha256 "9ef6c9ac3c8122fec2aa5bfcc4821548e5047faba1e9689dd49f1fd92b83ff97"

      def install
        bin.install "portfolio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shafi-/portfolio/releases/download/v0.3.0/portfolio-linux-amd64"
        sha256 "a8398b2ad14d361a66167b31d791222158a9b02b7325ec26fdb3c00fddff0997"

        def install
          bin.install "portfolio"
        end
      end
    end
  end

  test do
    system "#{bin}/portfolio --version"
  end
end
